"""empty message

Revision ID: 1a0a98eca7f9
Revises: 8c9898e1b130
Create Date: 2021-01-11 23:42:25.259833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a0a98eca7f9'
down_revision = '8c9898e1b130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree', sa.DateTime(), nullable=True),
    sa.Column('course_date', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('Course_teacher_id_fkey', 'Course', type_='foreignkey')
    op.drop_column('Course', 'teacher_id')
    op.drop_column('Course', 'course_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('course_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Course', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Course_teacher_id_fkey', 'Course', 'Teacher', ['teacher_id'], ['id'])
    op.drop_table('Event')
    # ### end Alembic commands ###
