"""empty message

Revision ID: 766d02600710
Revises: a0d168ce55cf
Create Date: 2021-01-12 00:13:50.509302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d02600710'
down_revision = 'a0d168ce55cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('tree', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event', 'tree')
    # ### end Alembic commands ###
