"""empty message

Revision ID: b809df36a5b3
Revises: 52e4bf49bd7e
Create Date: 2021-01-13 20:29:28.656621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b809df36a5b3'
down_revision = '52e4bf49bd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teacher', sa.Column('img_url', sa.String(), nullable=True))
    op.add_column('Tree', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tree', 'img_url')
    op.drop_column('Teacher', 'img_url')
    # ### end Alembic commands ###
